# need to install this on the ansibel host first pip install PyVmomi
- name: "VMware vDS and vLS deployments"
  hosts: localhost

  vars_files:
  - vars/ansible.yml
  - vars/port_grps.yml

  tasks:
  - block:
    # Creates each of the DVS
    - name: VMW >> Creating dvSwitch
      vmware_dvswitch:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        datacenter: "{{ item.dc }}"
        switch_name: "{{ item.name }}"
        version: 6.5.0
        # mtu: 1500
        uplink_quantity: 2
        discovery_protocol: lldp
        discovery_operation: both
        state: "{{ item.state }}"
      loop: "{{ dvs }}"
    # Creates each of the port-groups within each DVS
    - name: VMW >> Creating DvS port-groups
      connection: local
      vmware_dvs_portgroup:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        switch_name: "{{ item.0.name }}"
        portgroup_name: "{{ item.1.name }}"
        vlan_id: "{{ item.1.vlan }}"
        vlan_trunk: "{{ item.1.trunk | default(false) }}"
        num_ports: "{{ item.1.num_ports }}"
        portgroup_type: earlyBinding
        state: "{{ item.1.state }}"
        # teaming_policy:
        #   # Cant set the LDAP active and standy ports, that has to be done manually in vCentre
        #   load_balance_policy: loadbalance_ip
      loop: "{{ dvs | subelements('port_grp') }}"
    run_once: true
    delegate_to: localhost
    tags: dvs

  - block:
    # Creates each of the LVS
    - name: VMW >> Creating lvSwitch
      vmware_vswitch:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        esxi_hostname: "{{ item.esx_host }}"
        switch_name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ lvs }}"
    # Creates each of the port-groups within each LVS
    - name: Create vLS vlan portgroup
      vmware_portgroup:
        hostname: "{{ login.vcenter }}"
        username: "{{ login.user }}"
        password: "{{ login.pass }}"
        validate_certs: false
        esxi_hostname: "{{ item.0.esx_host }}"
        switch_name: "{{ item.0.name }}"
        portgroup_name: "{{ item.1.name }}"
        vlan_id: "{{ item.1.vlan }}"
        state: "{{ item.1.state }}"
      loop: "{{ lvs |subelements('port_grp') }}"
    run_once: true
    delegate_to: localhost
    tags: lvs