 # Creates each of the DVS
- name: VMW >> Creating Distributed vSwitches
  vmware_dvswitch:
    hostname: "{{ login.device }}"
    username: "{{ login.user }}"
    password: "{{ login.pass }}"
    validate_certs: false
    datacenter: "{{ item.esx_host_or_dc }}"
    switch_name: "{{ item.name }}"
    uplink_quantity: "{{ item.num_uplinks }}"
    state: "{{ item.state }}"
    # Omit ensures the dictionary is not used if it is empty
    mtu: "{{ item.mtu | default(omit) }}"
    discovery_protocol: "{{ item.discovery_ptcl| default(omit) }}"
    discovery_operation: "{{ item.discovery_oper | default(omit) }}"
  loop: "{{ flt_dvs.all_lvs }}"

# Creates each of the port-groups within each DVS
- name: VMW >> Creating DvS port-groups
  connection: local
  vmware_dvs_portgroup:
    hostname: "{{ login.device }}"
    username: "{{ login.user }}"
    password: "{{ login.pass }}"
    validate_certs: false
    switch_name: "{{ item.vs_name }}"
    portgroup_name: "{{ item.grp_name }}"
    vlan_id: "{{ item.vlan }}"
    vlan_trunk: "{{ item.trunk | default(true) }}"
    num_ports: "{{ item.num_ports | default(8) }}"
    portgroup_type: earlyBinding      # staticBinding
    state: "{{ item.state }}"
    # teaming_policy:
    #   # Cant set the LDAP active and standy ports, that has to be done manually in vCentre
    #   load_balance_policy: loadbalance_ip
  loop: "{{ flt_dvs.all_grp }}"
